insert into reader (username, first_name, last_name, title) values ('rdezamudio0', 'Rhett', 'De Zamudio', 'Dr');
insert into reader (username, first_name, last_name, title) values ('lliggett1', 'Leeanne', 'Liggett', 'Dr');
insert into reader (username, first_name, last_name, title) values ('tmathely2', 'Tyrone', 'Mathely', 'Mrs');
insert into reader (username, first_name, last_name, title) values ('lcuseck3', 'John', 'Cuseck', 'Ms');
insert into reader (username, first_name, last_name, title) values ('craith4', 'Cullen', 'Raith', 'Mrs');
insert into reader (username, first_name, last_name, title) values ('jfigure5', 'Jillana', 'Figure', 'Mrs');
insert into reader (username, first_name, last_name, title) values ('agerrens6', 'Alameda', 'Gerrens', 'Ms');
insert into reader (username, first_name, last_name, title) values ('tdefraine7', 'Tedmund', 'Defraine', 'Dr');
insert into reader (username, first_name, last_name, title) values ('estoeckle8', 'Erik', 'Stoeckle', null);
insert into reader (username, first_name, last_name, title) values ('pcarvil9', 'Peyter', 'Carvil', 'Mrs');
